import 'package:MediaPlus/APP_CONFIG/ApiUrlsData.dart';
import 'package:get/get_state_manager/get_state_manager.dart';

class PrimaryUserData {
  ///defaulst userId generated by db
  String userId;
  List followers = [];
  List followings = [];
  List blockedUsers = [];
  String name;
  String userName;
  String mobile;
  String bio;

  ///complete address of profile pic
  String profilePic;

  ///complete address of cover pic
  String coverPic;
  String email;

  jsonToModel(var jsonData) {
    print(jsonData);
    this.userId = jsonData["userdata"]["_id"];
    followers.addAll(jsonData["userdata"]["followers"]);
    followings.addAll(jsonData["userdata"]["following"]);
    blockedUsers.addAll(jsonData["userdata"]["blocked"]);
    this.name = jsonData["userdata"]["name"].toString();
    this.userName = jsonData["userdata"]["username"];
    this.mobile = jsonData["userdata"]["mobile"];
    this.bio = jsonData["userdata"]["bio"];
    this.profilePic = ApiUrlsData.domain + jsonData["userdata"]["profilePic"];
    this.coverPic = ApiUrlsData.domain + jsonData["userData"]["coverPic"];
    this.email = jsonData["userdata"]["email"];
  }

  static final PrimaryUserData primaryUserData = PrimaryUserData();

  String get getUserId => this.userId;

  set setUserId(String userId) => this.userId = userId;

  List<String> get getFollowers => this.followers;

  set addToFollowersList(String followerId) => this.followers.add(followerId);

  List<String> get getFollowings => this.followings;

  set addToFollowingsList(String followingId) =>
      this.followings.add(followingId);

  List<String> get getBlockedUsers => this.blockedUsers;

  set addToBlockedUsersList(String blockedUserId) =>
      this.blockedUsers.add(blockedUserId);

  String get getName => this.name;

  // set setName(String name) => this.name = name;

  String get getUserName => this.userName;

  void setUserName(String userName) {
    this.userName = userName;
  }

  String get getMobile => this.mobile;

  set setMobile(String mobile) => this.mobile = mobile;

  String get getBio => this.bio;

  String get getProfilePic => this.profilePic;

  String get getEmail => this.email;

  set setEmail(String email) => this.email = email;

  void setName(String name) {
    this.name = name;
  }

  void setBio(String bio) {
    this.bio = bio;
  }

  setProfilePic(String profilePic) {
    this.profilePic = ApiUrlsData.domain + profilePic;
  }

  setCoverPic(String coverPic) {
    this.coverPic = ApiUrlsData.domain + coverPic;
  }
}
